### ISSUE TITLE
Setup errors

### ISSUE THREAD

**Issue by mcchrish** [haruelrovix/rnw-github#5]
Hi Havit,

I can't seem to set up the application properly following instructions.

I get this error when running the web version:
```
❯ yarn web
yarn run v1.10.1
$ node scripts/start.js
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at Object.<anonymous> (/Users/mcchris/steve/code-review/havit/rnw-github/scripts/start.js:36:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And I get this error in android:
```
❯ yarn web
yarn run v1.10.1
$ node scripts/start.js
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at Object.<anonymous> (/Users/mcchris/steve/code-review/havit/rnw-github/scripts/start.js:36:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by haruelrovix** [comment]
Hi @mcchrish , could you please specify the `node, npm` version you're using?

Here's mine:
```
λ npm -v
5.6.0

λ node -v
v8.11.1

λ nvm list

  * 8.11.1 (Currently using 64-bit executable)
    6.11.1
```

**Comment by mcchrish** [comment]
```
❯ npm --versions
{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.33.0',
  node: '10.11.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.0',
  v8: '6.8.275.32-node.28',
  zlib: '1.2.11' }
```

Here's mine.

**Comment by haruelrovix** [comment]
@mcchrish Got it. Your node is `10.0.0` while mine is still at `8.11.1`.

```
λ nvm use 10.0.0
Now using node v10.0.0 (64-bit)

λ yarn web
yarn run v1.10.1
$ node scripts/start.js
fs.js:124
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.writeFile (fs.js:1244:14)
    ...
```

Let me update the code to use `10.0.0` 👌

**Comment by haruelrovix** [comment]
@mcchrish Could you please try [this branch](https://github.com/haruelrovix/rnw-github/tree/use-node-v10)?

```
$ git fetch
remote: Enumerating objects: 22, done.
...

$ git checkout use-node-v10
Switched to a new branch 'use-node-v10'
Branch 'use-node-v10' set up to track remote branch 'use-node-v10' from 'origin'.
```
